/* Autogenerated by MaKL - 2016年 06月 11日 星期六 00:26:53 CST */
/* Configure arguments: --prefix=/home/zhuxy/work/libu/libu --verbose --cross_compile */

#ifndef _LIBU_CONF_H_
#define _LIBU_CONF_H_

#undef LIBU_VERSION
#define LIBU_VERSION "2.3.0rc3"

#undef LIBU_VERSION_MAJOR
#define LIBU_VERSION_MAJOR 2

#undef LIBU_VERSION_MINOR
#define LIBU_VERSION_MINOR 3

#undef LIBU_VERSION_TEENY
#define LIBU_VERSION_TEENY 0

#undef OS_UNIX
#define OS_UNIX 1

#undef U_PATH_SEPARATOR
#define U_PATH_SEPARATOR '/'

#undef OS_LINUX
#define OS_LINUX 1

#undef HAVE_LONG_DOUBLE
#define HAVE_LONG_DOUBLE 1

#undef HAVE_LONG_LONG
#define HAVE_LONG_LONG 1

#undef HAVE_INTMAX_T
#define HAVE_INTMAX_T 1

#undef HAVE__BOOL
#define HAVE__BOOL 1

#undef HAVE_FLOAT__COMPLEX
#define HAVE_FLOAT__COMPLEX 1

#undef HAVE_DOUBLE__COMPLEX
#define HAVE_DOUBLE__COMPLEX 1

#undef HAVE_LONG_DOUBLE__COMPLEX
#define HAVE_LONG_DOUBLE__COMPLEX 1

#undef HAVE_PID_T
#define HAVE_PID_T 1

#undef HAVE_SSIZE_T
#define HAVE_SSIZE_T 1

#undef HAVE_SOCKLEN_T
#define HAVE_SOCKLEN_T 1

#undef HAVE_IN_ADDR_T
#define HAVE_IN_ADDR_T 1

#undef HAVE_STRUCT_RUSAGE
#define HAVE_STRUCT_RUSAGE 1

#undef HAVE_TCP_NODELAY
#define HAVE_TCP_NODELAY 1

#undef HAVE_INET_ADDRSTRLEN
#define HAVE_INET_ADDRSTRLEN 1

#undef HAVE_SO_BROADCAST
#define HAVE_SO_BROADCAST 1

#undef HAVE_MAP_FIXED
#define HAVE_MAP_FIXED 1

#undef HAVE_DAEMON
#define HAVE_DAEMON 1

#undef HAVE_SETSOCKOPT
#define HAVE_SETSOCKOPT 1

#undef HAVE_GETSOCKOPT
#define HAVE_GETSOCKOPT 1

#undef HAVE_GETPID
#define HAVE_GETPID 1

#undef HAVE_LINK
#define HAVE_LINK 1

#undef HAVE_UNLINK
#define HAVE_UNLINK 1

#undef HAVE_SLEEP
#define HAVE_SLEEP 1

#undef HAVE_MKSTEMPS
#define HAVE_MKSTEMPS 1

#undef HAVE_SETENV
#define HAVE_SETENV 1

#undef HAVE_MMAP
#define HAVE_MMAP 1

#undef HAVE_FCNTL
#define HAVE_FCNTL 1

#undef HAVE_SYSCONF
#define HAVE_SYSCONF 1

#undef HAVE_GETPAGESIZE
#define HAVE_GETPAGESIZE 1

#undef HAVE_FNMATCH
#define HAVE_FNMATCH 1

#undef HAVE_STRTOK_R
#define HAVE_STRTOK_R 1

#undef HAVE_STRSEP
#define HAVE_STRSEP 1

#undef HAVE_STRLCPY
#define HAVE_STRLCPY 1

#undef HAVE_STRLCAT
#define HAVE_STRLCAT 1

#undef HAVE_STRTOD
#define HAVE_STRTOD 1

#undef HAVE_GETTIMEOFDAY
#define HAVE_GETTIMEOFDAY 1

#undef HAVE_TIMEGM
#define HAVE_TIMEGM 1

#undef HAVE_SYSLOG
#define HAVE_SYSLOG 1

#undef HAVE_VSYSLOG

#undef HAVE_STRTOUMAX
#define HAVE_STRTOUMAX 1

#undef HAVE_GETADDRINFO
#define HAVE_GETADDRINFO 1

#undef HAVE_UNAME
#define HAVE_UNAME 1

#undef HAVE_FORK
#define HAVE_FORK 1

#undef HAVE_WAIT3
#define HAVE_WAIT3 1

#undef HAVE_WAIT
#define HAVE_WAIT 1

#undef HAVE_SIGACTION
#define HAVE_SIGACTION 1

#undef HAVE_SETITIMER
#define HAVE_SETITIMER 1

#undef HAVE_ISFINITE
#define HAVE_ISFINITE 1

#undef HAVE_STRERROR_R
#define HAVE_STRERROR_R 1

#undef HAVE_COMPLEX
//#define HAVE_COMPLEX 1

#undef HAVE_UNISTD
#define HAVE_UNISTD 1

#undef HAVE_STDLIB
#define HAVE_STDLIB 1

#undef HAVE_PATHS
#define HAVE_PATHS 1

#undef HAVE_SYSUIO
#define HAVE_SYSUIO 1

#undef HAVE_STRINGS
#define HAVE_STRINGS 1

#undef HAVE_SYS_SOCKET
#define HAVE_SYS_SOCKET 1

#undef HAVE_NETINET_IN
#define HAVE_NETINET_IN 1

#undef HAVE_NETINET_TCP
#define HAVE_NETINET_TCP 1

#undef HAVE_TMZONE
#define HAVE_TMZONE 1

#undef HAVE_OPTARG
#define HAVE_OPTARG 1

#undef HAVE_OPTIND
#define HAVE_OPTIND 1

#undef HAVE_INLINE
#define HAVE_INLINE 1

#undef HAVE_DOXYGEN

#undef DESTDIR
#define DESTDIR "/home/zhuxy/work/libu/libu"

#undef BINDIR
#define BINDIR "/home/zhuxy/work/libu/libu/bin"

#undef SBINDIR
#define SBINDIR "/home/zhuxy/work/libu/libu/sbin"

#undef CONFDIR
#define CONFDIR "/home/zhuxy/work/libu/libu/etc"

#undef INCDIR
#define INCDIR /home/zhuxy/work/libu/libu/include/u

#undef LIBDIR
#define LIBDIR "/home/zhuxy/work/libu/libu/lib"

#undef SHLIBDIR
#define SHLIBDIR "/home/zhuxy/work/libu/libu/lib"

#undef LIBEXDIR
#define LIBEXDIR "/home/zhuxy/work/libu/libu/libexec"

#undef VARDIR
#define VARDIR "/home/zhuxy/work/libu/libu/var"

#undef SHAREDIR
#define SHAREDIR "/home/zhuxy/work/libu/libu/share"

#undef MANDIR
#define MANDIR "/home/zhuxy/work/libu/libu/share/man"

#undef DOCDIR
#define DOCDIR "/home/zhuxy/work/libu/libu/share/doc"

#undef HAVE_STRUCT_SOCKADDR_IN
#define HAVE_STRUCT_SOCKADDR_IN 1

#undef HAVE_STRUCT_SOCKADDR_IN6
#define HAVE_STRUCT_SOCKADDR_IN6 1

#undef HAVE_STRUCT_SOCKADDR_UN
#define HAVE_STRUCT_SOCKADDR_UN 1

#undef HAVE_NETINET_SCTP

#undef NO_SCTP
#define NO_SCTP 1

#endif /* !_LIBU_CONF_H_ */
